# Generated by Django 2.1.15 on 2020-02-11 19:54

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_data', django_mysql.models.JSONField(default=dict, null=True)),
                ('request_type', models.CharField(max_length=128)),
                ('url_path', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_data', django_mysql.models.JSONField(default=dict, null=True)),
                ('response_status', models.PositiveIntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='logs.RequestLog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
